/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManifestRouteImport } from './routes/manifest'
import { Route as ImportRouteImport } from './routes/import'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStreamProxyRouteImport } from './routes/api/stream-proxy'
import { Route as ApiSoundcloudProxyRouteImport } from './routes/api/soundcloud-proxy'
import { Route as ApiLoadPlatformItemRouteImport } from './routes/api/load-platform-item'
import { Route as ApiBandcampProxyRouteImport } from './routes/api/bandcamp-proxy'

const ManifestRoute = ManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamProxyRoute = ApiStreamProxyRouteImport.update({
  id: '/api/stream-proxy',
  path: '/api/stream-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoundcloudProxyRoute = ApiSoundcloudProxyRouteImport.update({
  id: '/api/soundcloud-proxy',
  path: '/api/soundcloud-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoadPlatformItemRoute = ApiLoadPlatformItemRouteImport.update({
  id: '/api/load-platform-item',
  path: '/api/load-platform-item',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBandcampProxyRoute = ApiBandcampProxyRouteImport.update({
  id: '/api/bandcamp-proxy',
  path: '/api/bandcamp-proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/manifest': typeof ManifestRoute
  '/api/bandcamp-proxy': typeof ApiBandcampProxyRoute
  '/api/load-platform-item': typeof ApiLoadPlatformItemRoute
  '/api/soundcloud-proxy': typeof ApiSoundcloudProxyRoute
  '/api/stream-proxy': typeof ApiStreamProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/manifest': typeof ManifestRoute
  '/api/bandcamp-proxy': typeof ApiBandcampProxyRoute
  '/api/load-platform-item': typeof ApiLoadPlatformItemRoute
  '/api/soundcloud-proxy': typeof ApiSoundcloudProxyRoute
  '/api/stream-proxy': typeof ApiStreamProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/manifest': typeof ManifestRoute
  '/api/bandcamp-proxy': typeof ApiBandcampProxyRoute
  '/api/load-platform-item': typeof ApiLoadPlatformItemRoute
  '/api/soundcloud-proxy': typeof ApiSoundcloudProxyRoute
  '/api/stream-proxy': typeof ApiStreamProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/manifest'
    | '/api/bandcamp-proxy'
    | '/api/load-platform-item'
    | '/api/soundcloud-proxy'
    | '/api/stream-proxy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/manifest'
    | '/api/bandcamp-proxy'
    | '/api/load-platform-item'
    | '/api/soundcloud-proxy'
    | '/api/stream-proxy'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/manifest'
    | '/api/bandcamp-proxy'
    | '/api/load-platform-item'
    | '/api/soundcloud-proxy'
    | '/api/stream-proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  ManifestRoute: typeof ManifestRoute
  ApiBandcampProxyRoute: typeof ApiBandcampProxyRoute
  ApiLoadPlatformItemRoute: typeof ApiLoadPlatformItemRoute
  ApiSoundcloudProxyRoute: typeof ApiSoundcloudProxyRoute
  ApiStreamProxyRoute: typeof ApiStreamProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manifest': {
      id: '/manifest'
      path: '/manifest'
      fullPath: '/manifest'
      preLoaderRoute: typeof ManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream-proxy': {
      id: '/api/stream-proxy'
      path: '/api/stream-proxy'
      fullPath: '/api/stream-proxy'
      preLoaderRoute: typeof ApiStreamProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/soundcloud-proxy': {
      id: '/api/soundcloud-proxy'
      path: '/api/soundcloud-proxy'
      fullPath: '/api/soundcloud-proxy'
      preLoaderRoute: typeof ApiSoundcloudProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/load-platform-item': {
      id: '/api/load-platform-item'
      path: '/api/load-platform-item'
      fullPath: '/api/load-platform-item'
      preLoaderRoute: typeof ApiLoadPlatformItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bandcamp-proxy': {
      id: '/api/bandcamp-proxy'
      path: '/api/bandcamp-proxy'
      fullPath: '/api/bandcamp-proxy'
      preLoaderRoute: typeof ApiBandcampProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  ManifestRoute: ManifestRoute,
  ApiBandcampProxyRoute: ApiBandcampProxyRoute,
  ApiLoadPlatformItemRoute: ApiLoadPlatformItemRoute,
  ApiSoundcloudProxyRoute: ApiSoundcloudProxyRoute,
  ApiStreamProxyRoute: ApiStreamProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
