/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TunnelRouteImport } from './routes/tunnel'
import { Route as PlaylistDotm3uRouteImport } from './routes/playlist[.]m3u'
import { Route as ManifestRouteImport } from './routes/manifest'
import { Route as ImportRouteImport } from './routes/import'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStreamProxyRouteImport } from './routes/api/stream-proxy'
import { Route as ApiStationsDotjsonRouteImport } from './routes/api/stations[.]json'
import { Route as ApiSoundcloudProxyRouteImport } from './routes/api/soundcloud-proxy'
import { Route as ApiRadioMetadataRouteImport } from './routes/api/radio-metadata'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiBandcampProxyRouteImport } from './routes/api/bandcamp-proxy'

const TunnelRoute = TunnelRouteImport.update({
  id: '/tunnel',
  path: '/tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistDotm3uRoute = PlaylistDotm3uRouteImport.update({
  id: '/playlist.m3u',
  path: '/playlist.m3u',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestRoute = ManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamProxyRoute = ApiStreamProxyRouteImport.update({
  id: '/api/stream-proxy',
  path: '/api/stream-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStationsDotjsonRoute = ApiStationsDotjsonRouteImport.update({
  id: '/api/stations.json',
  path: '/api/stations.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoundcloudProxyRoute = ApiSoundcloudProxyRouteImport.update({
  id: '/api/soundcloud-proxy',
  path: '/api/soundcloud-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRadioMetadataRoute = ApiRadioMetadataRouteImport.update({
  id: '/api/radio-metadata',
  path: '/api/radio-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBandcampProxyRoute = ApiBandcampProxyRouteImport.update({
  id: '/api/bandcamp-proxy',
  path: '/api/bandcamp-proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/manifest': typeof ManifestRoute
  '/playlist.m3u': typeof PlaylistDotm3uRoute
  '/tunnel': typeof TunnelRoute
  '/api/bandcamp-proxy': typeof ApiBandcampProxyRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/radio-metadata': typeof ApiRadioMetadataRoute
  '/api/soundcloud-proxy': typeof ApiSoundcloudProxyRoute
  '/api/stations.json': typeof ApiStationsDotjsonRoute
  '/api/stream-proxy': typeof ApiStreamProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/manifest': typeof ManifestRoute
  '/playlist.m3u': typeof PlaylistDotm3uRoute
  '/tunnel': typeof TunnelRoute
  '/api/bandcamp-proxy': typeof ApiBandcampProxyRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/radio-metadata': typeof ApiRadioMetadataRoute
  '/api/soundcloud-proxy': typeof ApiSoundcloudProxyRoute
  '/api/stations.json': typeof ApiStationsDotjsonRoute
  '/api/stream-proxy': typeof ApiStreamProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/manifest': typeof ManifestRoute
  '/playlist.m3u': typeof PlaylistDotm3uRoute
  '/tunnel': typeof TunnelRoute
  '/api/bandcamp-proxy': typeof ApiBandcampProxyRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/radio-metadata': typeof ApiRadioMetadataRoute
  '/api/soundcloud-proxy': typeof ApiSoundcloudProxyRoute
  '/api/stations.json': typeof ApiStationsDotjsonRoute
  '/api/stream-proxy': typeof ApiStreamProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/manifest'
    | '/playlist.m3u'
    | '/tunnel'
    | '/api/bandcamp-proxy'
    | '/api/feedback'
    | '/api/radio-metadata'
    | '/api/soundcloud-proxy'
    | '/api/stations.json'
    | '/api/stream-proxy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/manifest'
    | '/playlist.m3u'
    | '/tunnel'
    | '/api/bandcamp-proxy'
    | '/api/feedback'
    | '/api/radio-metadata'
    | '/api/soundcloud-proxy'
    | '/api/stations.json'
    | '/api/stream-proxy'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/manifest'
    | '/playlist.m3u'
    | '/tunnel'
    | '/api/bandcamp-proxy'
    | '/api/feedback'
    | '/api/radio-metadata'
    | '/api/soundcloud-proxy'
    | '/api/stations.json'
    | '/api/stream-proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  ManifestRoute: typeof ManifestRoute
  PlaylistDotm3uRoute: typeof PlaylistDotm3uRoute
  TunnelRoute: typeof TunnelRoute
  ApiBandcampProxyRoute: typeof ApiBandcampProxyRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiRadioMetadataRoute: typeof ApiRadioMetadataRoute
  ApiSoundcloudProxyRoute: typeof ApiSoundcloudProxyRoute
  ApiStationsDotjsonRoute: typeof ApiStationsDotjsonRoute
  ApiStreamProxyRoute: typeof ApiStreamProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tunnel': {
      id: '/tunnel'
      path: '/tunnel'
      fullPath: '/tunnel'
      preLoaderRoute: typeof TunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist.m3u': {
      id: '/playlist.m3u'
      path: '/playlist.m3u'
      fullPath: '/playlist.m3u'
      preLoaderRoute: typeof PlaylistDotm3uRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest': {
      id: '/manifest'
      path: '/manifest'
      fullPath: '/manifest'
      preLoaderRoute: typeof ManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream-proxy': {
      id: '/api/stream-proxy'
      path: '/api/stream-proxy'
      fullPath: '/api/stream-proxy'
      preLoaderRoute: typeof ApiStreamProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stations.json': {
      id: '/api/stations.json'
      path: '/api/stations.json'
      fullPath: '/api/stations.json'
      preLoaderRoute: typeof ApiStationsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/soundcloud-proxy': {
      id: '/api/soundcloud-proxy'
      path: '/api/soundcloud-proxy'
      fullPath: '/api/soundcloud-proxy'
      preLoaderRoute: typeof ApiSoundcloudProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/radio-metadata': {
      id: '/api/radio-metadata'
      path: '/api/radio-metadata'
      fullPath: '/api/radio-metadata'
      preLoaderRoute: typeof ApiRadioMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bandcamp-proxy': {
      id: '/api/bandcamp-proxy'
      path: '/api/bandcamp-proxy'
      fullPath: '/api/bandcamp-proxy'
      preLoaderRoute: typeof ApiBandcampProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  ManifestRoute: ManifestRoute,
  PlaylistDotm3uRoute: PlaylistDotm3uRoute,
  TunnelRoute: TunnelRoute,
  ApiBandcampProxyRoute: ApiBandcampProxyRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiRadioMetadataRoute: ApiRadioMetadataRoute,
  ApiSoundcloudProxyRoute: ApiSoundcloudProxyRoute,
  ApiStationsDotjsonRoute: ApiStationsDotjsonRoute,
  ApiStreamProxyRoute: ApiStreamProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
