import {
  delayFractionOptions,
  tidalFractionOptions,
} from "./effect-definition-shared.js";
import { defineEffect } from "./param-types.js";

export const TIME_SPACE_EFFECT_DEFINITIONS = {
  cheapReverb: defineEffect({
    defaultConfig: {
      damp: 0.5,
      damping: 0.5,
      decay: 0.5,
      dry: -72,
      dryWet: 0.35,
      enabled: false,
      filter: 0,
      inputGain: 1,
      outputGain: 1,
      preDelay: 0.001,
      roomSize: 0.5,
      type: "cheapReverb",
      wet: 0,
      width: 1,
    },
    description: "Lightweight FreeVerb-style room reverb",
    name: "Free Reverb",
    params: [
      {
        formatKey: "percentage",
        key: "decay",
        label: "Decay",
        max: 1,
        min: 0,
        step: 0.01,
        type: "slider",
      },
      {
        formatKey: "time",
        key: "preDelay",
        label: "Pre-delay",
        max: 0.5,
        min: 0.001,
        step: 0.001,
        type: "slider",
      },
      {
        formatKey: "percentage",
        key: "damp",
        label: "Damp",
        max: 1,
        min: 0,
        step: 0.01,
        type: "slider",
      },
      {
        formatKey: "percentage",
        key: "filter",
        label: "Filter",
        max: 1,
        min: -1,
        step: 0.01,
        type: "slider",
      },
      {
        children: [
          {
            description:
              "Native dry level inside the reverb; independent of the outer Effect Mix.",
            formatKey: "db",
            key: "dry",
            label: "Device Dry",
            max: 12,
            min: -72,
            step: 0.1,
            type: "slider",
          },
          {
            description:
              "Native reverb-return level before the outer Effect Mix.",
            formatKey: "db",
            key: "wet",
            label: "Device Wet",
            max: 12,
            min: -72,
            step: 0.1,
            type: "slider",
          },
        ],
        title: "Mix",
        type: "group",
      },
    ],
    type: "cheapReverb",
  }),

  delay: defineEffect({
    defaultConfig: {
      cross: 1,
      crossFeedback: 0,
      delayMillis: 0,
      delayMusical: "1/4",
      delayTime: 0.3,
      dry: -72,
      dryWet: 1.0,
      enabled: false,
      feedback: 0.5,
      filter: 0,
      filterFrequency: 12_000,
      inputGain: 1.0,
      lfoDepth: 0,
      lfoRate: 0,
      lfoSpeed: 0.1,
      outputGain: 1.0,
      preDelay: 0,
      preMillisTimeLeft: 0,
      preMillisTimeRight: 0,
      preSyncTimeLeft: "1/16",
      preSyncTimeRight: "Off",
      tempoDivision: "1/4",
      tempoSync: false,
      type: "delay",
      wet: 0,
    },
    description: "Tempo-syncable stereo delay with filtering and modulation",
    name: "Delay",
    params: [
      {
        children: [
          {
            key: "delayMusical",
            label: "Musical delay",
            options: delayFractionOptions,
            type: "select",
          },
          {
            formatKey: "milliseconds",
            key: "delayMillis",
            label: "Additional delay",
            max: 1000,
            min: 0,
            step: 0.1,
            type: "slider",
          },
        ],
        title: "Main Delay",
        type: "group",
      },
      {
        children: [
          {
            key: "preSyncTimeLeft",
            label: "Left sync",
            options: delayFractionOptions,
            type: "select",
          },
          {
            formatKey: "milliseconds",
            key: "preMillisTimeLeft",
            label: "Left milliseconds",
            max: 1000,
            min: 0,
            step: 0.1,
            type: "slider",
          },
          {
            key: "preSyncTimeRight",
            label: "Right sync",
            options: delayFractionOptions,
            type: "select",
          },
          {
            formatKey: "milliseconds",
            key: "preMillisTimeRight",
            label: "Right milliseconds",
            max: 1000,
            min: 0,
            step: 0.1,
            type: "slider",
          },
        ],
        title: "Pre-delay",
        type: "group",
      },
      {
        formatKey: "percentage",
        key: "feedback",
        label: "Feedback",
        max: 1,
        min: 0,
        step: 0.01,
        type: "slider",
      },
      {
        formatKey: "percentage",
        key: "cross",
        label: "Cross-feedback",
        max: 1,
        min: 0,
        step: 0.01,
        type: "slider",
      },
      {
        formatKey: "percentage",
        key: "filter",
        label: "Filter",
        max: 1,
        min: -1,
        step: 0.01,
        type: "slider",
      },
      {
        children: [
          {
            formatKey: "hz",
            key: "lfoSpeed",
            label: "LFO rate",
            max: 5,
            min: 0.1,
            step: 0.01,
            type: "slider",
          },
          {
            formatKey: "milliseconds",
            key: "lfoDepth",
            label: "LFO depth",
            max: 50,
            min: 0,
            step: 0.1,
            type: "slider",
          },
        ],
        title: "Modulation",
        type: "group",
      },
      {
        children: [
          {
            description:
              "Native dry level inside the delay; independent of the outer Effect Mix.",
            formatKey: "db",
            key: "dry",
            label: "Device Dry",
            max: 12,
            min: -72,
            step: 0.1,
            type: "slider",
          },
          {
            description:
              "Native delay-return level before the outer Effect Mix.",
            formatKey: "db",
            key: "wet",
            label: "Device Wet",
            max: 12,
            min: -72,
            step: 0.1,
            type: "slider",
          },
        ],
        title: "Mix",
        type: "group",
      },
    ],
    type: "delay",
  }),
  plateReverb: defineEffect({
    defaultConfig: {
      bandwidth: 0.9999,
      damping: 0.005,
      decay: 0.5,
      decayDiffusion1: 0.7,
      decayDiffusion2: 0.5,
      dry: -72,
      dryWet: 1.0,
      enabled: false,
      excursionDepth: 0.7,
      excursionRate: 0.5,
      inputDiffusion1: 0.75,
      inputDiffusion2: 0.625,
      inputGain: 1.0,
      outputGain: 1.0,
      preDelayMillis: 0,
      type: "plateReverb",
      wet: 0,
    },
    description: "Advanced plate reverb with extensive controls",
    name: "Dattorro Reverb",
    params: [
      {
        children: [
          {
            formatKey: "milliseconds",
            key: "preDelayMillis",
            label: "Pre-Delay",
            max: 1000,
            min: 0,
            step: 1,
            type: "slider",
          },
          {
            formatKey: "default",
            key: "bandwidth",
            label: "Bandwidth",
            max: 1,
            min: 0,
            step: 0.0001,
            type: "slider",
          },
        ],
        title: "Pre-Delay & Bandwidth",
        type: "group",
      },
      {
        children: [
          {
            formatKey: "default",
            key: "inputDiffusion1",
            label: "Input Diffusion 1",
            max: 1,
            min: 0,
            step: 0.01,
            type: "slider",
          },
          {
            formatKey: "default",
            key: "inputDiffusion2",
            label: "Input Diffusion 2",
            max: 1,
            min: 0,
            step: 0.01,
            type: "slider",
          },
        ],
        title: "Input Diffusion",
        type: "group",
      },
      {
        children: [
          {
            formatKey: "default",
            key: "decay",
            label: "Decay",
            max: 1,
            min: 0,
            step: 0.01,
            type: "slider",
          },
          {
            formatKey: "default",
            key: "decayDiffusion1",
            label: "Decay Diffusion 1",
            max: 0.999_999,
            min: 0,
            step: 0.001,
            type: "slider",
          },
          {
            formatKey: "default",
            key: "decayDiffusion2",
            label: "Decay Diffusion 2",
            max: 0.999_999,
            min: 0,
            step: 0.001,
            type: "slider",
          },
        ],
        title: "Decay",
        type: "group",
      },
      {
        children: [
          {
            formatKey: "default",
            key: "damping",
            label: "Damping",
            max: 1,
            min: 0,
            step: 0.001,
            type: "slider",
          },
          {
            formatKey: "default",
            key: "excursionRate",
            label: "Excursion Rate",
            max: 2,
            min: 0,
            step: 0.01,
            type: "slider",
          },
          {
            formatKey: "default",
            key: "excursionDepth",
            label: "Excursion Depth",
            max: 2,
            min: 0,
            step: 0.01,
            type: "slider",
          },
        ],
        title: "Modulation",
        type: "group",
      },
      {
        children: [
          {
            description:
              "Native dry level inside the reverb; independent of the outer Effect Mix.",
            formatKey: "db",
            key: "dry",
            label: "Device Dry",
            max: 12,
            min: -72,
            step: 0.1,
            type: "slider",
          },
          {
            description:
              "Native reverb-return level before the outer Effect Mix.",
            formatKey: "db",
            key: "wet",
            label: "Device Wet",
            max: 12,
            min: -72,
            step: 0.1,
            type: "slider",
          },
        ],
        title: "Mix",
        type: "group",
      },
    ],
    type: "plateReverb",
  }),

  tidal: defineEffect({
    defaultConfig: {
      channelOffset: 0,
      depth: 0.75,
      dryWet: 1.0,
      enabled: false,
      inputGain: 1.0,
      offset: 0,
      outputGain: 1.0,
      rate: 1.0,
      rateDivision: "1/4",
      slope: -0.25,
      symmetry: 0.5,
      tempoDivision: "1/4",
      tempoSync: true,
      type: "tidal",
    },
    description:
      "Rhythm shaping effect with rate, depth, slope, symmetry, and phase controls",
    name: "Tidal",
    params: [
      {
        key: "rateDivision",
        label: "Rate",
        options: tidalFractionOptions,
        type: "select",
      },
      {
        formatKey: "percentage",
        key: "depth",
        label: "Depth",
        max: 1,
        min: 0,
        step: 0.01,
        type: "slider",
      },
      {
        formatKey: "percentage",
        key: "slope",
        label: "Slope",
        max: 1,
        min: -1,
        step: 0.01,
        type: "slider",
      },
      {
        formatKey: "percentage",
        key: "symmetry",
        label: "Symmetry",
        max: 1,
        min: 0,
        step: 0.01,
        type: "slider",
      },
      {
        children: [
          {
            formatKey: "degrees",
            key: "offset",
            label: "Offset",
            max: 180,
            min: -180,
            step: 1,
            type: "slider",
          },
          {
            formatKey: "degrees",
            key: "channelOffset",
            label: "Channel Offset",
            max: 180,
            min: -180,
            step: 1,
            type: "slider",
          },
        ],
        title: "Phase",
        type: "group",
      },
    ],
    type: "tidal",
  }),
} as const;
