import {
  vocoderBandOptions,
  vocoderModulatorOptions,
} from "./effect-definition-shared.js";
import { defineEffect } from "./param-types.js";

export const DYNAMICS_EFFECT_DEFINITIONS = {
  compressor: defineEffect({
    defaultConfig: {
      attack: 2,
      autoAttack: false,
      autoattack: false,
      autoMakeup: true,
      automakeup: true,
      autoRelease: false,
      autorelease: false,
      dryWet: 1.0,
      enabled: false,
      inputGain: 1.0,
      inputgain: 0,
      knee: 6,
      lookahead: false,
      makeup: 0,
      mix: 1,
      outputGain: 1.0,
      ratio: 4,
      release: 140,
      threshold: -10,
      type: "compressor",
    },
    description:
      "Professional dynamics compressor with lookahead and auto attack/release",
    name: "Compressor",
    params: [
      {
        children: [
          {
            formatKey: "db",
            key: "threshold",
            label: "Threshold",
            max: 0,
            min: -60,
            step: 0.5,
            type: "slider",
          },
          {
            formatKey: "ratio",
            key: "ratio",
            label: "Ratio",
            max: 24,
            min: 1,
            step: 0.1,
            type: "slider",
          },
        ],
        title: "Threshold & Ratio",
        type: "group",
      },
      {
        children: [
          {
            formatKey: "milliseconds",
            key: "attack",
            label: "Attack",
            max: 100,
            min: 0,
            step: 0.1,
            type: "slider",
          },
          {
            formatKey: "milliseconds",
            key: "release",
            label: "Release",
            max: 1500,
            min: 5,
            step: 1,
            type: "slider",
          },
        ],
        title: "Timing",
        type: "group",
      },
      {
        formatKey: "db",
        key: "knee",
        label: "Knee",
        max: 24,
        min: 0,
        step: 0.5,
        type: "slider",
      },
      {
        description:
          "Gain applied by the compressor after reduction and before the wrapper.",
        formatKey: "db",
        key: "makeup",
        label: "Device Makeup Gain",
        max: 40,
        min: -40,
        step: 0.5,
        type: "slider",
      },
      {
        description:
          "Parallel blend inside the compressor; Effect Mix remains the outer wrapper blend.",
        formatKey: "percentage",
        key: "mix",
        label: "Device Mix",
        max: 1,
        min: 0,
        step: 0.01,
        type: "slider",
      },
      {
        description:
          "Drives the compressor detector and processor before the wrapper mix.",
        formatKey: "db",
        key: "inputgain",
        label: "Device Input Gain",
        max: 30,
        min: -30,
        step: 0.1,
        type: "slider",
      },
      {
        children: [
          {
            description: "Enable lookahead for better transient handling",
            key: "lookahead",
            label: "Lookahead (5ms)",
            type: "checkbox",
          },
          {
            description: "Automatically adjust attack based on crest factor",
            key: "autoattack",
            label: "Auto Attack",
            type: "checkbox",
          },
          {
            description: "Automatically adjust release based on crest factor",
            key: "autorelease",
            label: "Auto Release",
            type: "checkbox",
          },
          {
            description: "Automatically compensate for gain reduction",
            key: "automakeup",
            label: "Auto Makeup",
            type: "checkbox",
          },
        ],
        title: "Auto Controls",
        type: "group",
      },
    ],
    type: "compressor",
    visualization: "compressor-curve",
  }),

  gate: defineEffect({
    defaultConfig: {
      attack: 1,
      dryWet: 1,
      enabled: false,
      floor: -72,
      hold: 50,
      inputGain: 1,
      inverse: false,
      outputGain: 1,
      release: 100,
      return: 0,
      threshold: -6,
      type: "gate",
    },
    description: "Noise gate with hold, floor, inverse, and sidechain support",
    name: "Gate",
    params: [
      {
        formatKey: "db",
        key: "threshold",
        label: "Threshold",
        max: 0,
        min: -80,
        step: 0.5,
        type: "slider",
      },
      {
        formatKey: "db",
        key: "return",
        label: "Return",
        max: 24,
        min: 0,
        step: 0.1,
        type: "slider",
      },
      {
        children: [
          {
            formatKey: "milliseconds",
            key: "attack",
            label: "Attack",
            max: 1000,
            min: 0,
            step: 0.1,
            type: "slider",
          },
          {
            formatKey: "milliseconds",
            key: "hold",
            label: "Hold",
            max: 500,
            min: 0,
            step: 1,
            type: "slider",
          },
          {
            formatKey: "milliseconds",
            key: "release",
            label: "Release",
            max: 2000,
            min: 1,
            step: 1,
            type: "slider",
          },
        ],
        title: "Envelope",
        type: "group",
      },
      {
        formatKey: "db",
        key: "floor",
        label: "Floor",
        max: 0,
        min: -72,
        step: 0.5,
        type: "slider",
      },
      {
        description: "Duck the signal when the detector opens",
        key: "inverse",
        label: "Inverse",
        type: "checkbox",
      },
    ],
    type: "gate",
  }),

  limiter: defineEffect({
    defaultConfig: {
      dryWet: 1.0,
      enabled: false,
      inputGain: 1.0,
      outputGain: 1.0,
      threshold: 0,
      type: "limiter",
    },
    description: "Transparent brick-wall limiter for output protection",
    name: "Limiter",
    params: [
      {
        children: [
          {
            formatKey: "db",
            key: "threshold",
            label: "Threshold",
            max: 0,
            min: -60,
            step: 0.1,
            type: "slider",
          },
        ],
        title: "Limiter",
        type: "group",
      },
    ],
    type: "limiter",
  }),

  maximizer: defineEffect({
    defaultConfig: {
      ceiling: -0.1,
      dryWet: 1,
      enabled: false,
      inputGain: 1,
      lookahead: 5,
      lookaheadEnabled: true,
      outputGain: 1,
      release: 100,
      threshold: -6,
      type: "maximizer",
    },
    description: "Lookahead brickwall limiter with automatic makeup",
    name: "Maximizer",
    params: [
      {
        formatKey: "db",
        key: "threshold",
        label: "Threshold",
        max: 0,
        min: -24,
        step: 0.1,
        type: "slider",
      },
      {
        key: "lookaheadEnabled",
        label: "Lookahead",
        type: "checkbox",
      },
    ],
    type: "maximizer",
  }),

  vocoder: defineEffect({
    defaultConfig: {
      bandCount: 16,
      bands: 16,
      carrierGain: 1,
      carrierMaxFreq: 12_000,
      carrierMinFreq: 100,
      dryWet: 1,
      enabled: false,
      envAttack: 5,
      envRelease: 30,
      gain: 0,
      inputGain: 1,
      mix: 1,
      modulator: "self",
      modulatorGain: 1,
      modulatorMaxFreq: 12_000,
      modulatorMinFreq: 100,
      modulatorSource: "noise-pink",
      noise: 0,
      outputGain: 1,
      qEnd: 2,
      qStart: 20,
      type: "vocoder",
    },
    description: "Multiband vocoder with noise, self, or external modulator",
    name: "Vocoder",
    params: [
      {
        key: "bandCount",
        label: "Bands",
        options: vocoderBandOptions,
        type: "select",
        valueType: "number",
      },
      {
        key: "modulatorSource",
        label: "Modulator",
        options: vocoderModulatorOptions,
        type: "select",
      },
      {
        children: [
          {
            formatKey: "frequency",
            key: "carrierMinFreq",
            label: "Minimum",
            max: 20_000,
            min: 20,
            step: 1,
            type: "slider",
          },
          {
            formatKey: "frequency",
            key: "carrierMaxFreq",
            label: "Maximum",
            max: 20_000,
            min: 20,
            step: 1,
            type: "slider",
          },
        ],
        title: "Carrier range",
        type: "group",
      },
      {
        children: [
          {
            formatKey: "frequency",
            key: "modulatorMinFreq",
            label: "Minimum",
            max: 20_000,
            min: 20,
            step: 1,
            type: "slider",
          },
          {
            formatKey: "frequency",
            key: "modulatorMaxFreq",
            label: "Maximum",
            max: 20_000,
            min: 20,
            step: 1,
            type: "slider",
          },
        ],
        title: "Modulator range",
        type: "group",
      },
      {
        children: [
          {
            key: "qStart",
            label: "Q start",
            max: 60,
            min: 1,
            step: 0.1,
            type: "slider",
          },
          {
            key: "qEnd",
            label: "Q end",
            max: 60,
            min: 1,
            step: 0.1,
            type: "slider",
          },
        ],
        title: "Filter bank",
        type: "group",
      },
      {
        children: [
          {
            formatKey: "milliseconds",
            key: "envAttack",
            label: "Attack",
            max: 100,
            min: 0.1,
            step: 0.1,
            type: "slider",
          },
          {
            formatKey: "milliseconds",
            key: "envRelease",
            label: "Release",
            max: 1000,
            min: 1,
            step: 1,
            type: "slider",
          },
        ],
        title: "Envelope",
        type: "group",
      },
      {
        description:
          "Native vocoder output level before the outer wrapper and Post-FX Trim.",
        formatKey: "db",
        key: "gain",
        label: "Device Output Gain",
        max: 20,
        min: -20,
        step: 0.1,
        type: "slider",
      },
      {
        description:
          "Blend inside the vocoder; Effect Mix remains the outer wrapper blend.",
        formatKey: "percentage",
        key: "mix",
        label: "Device Mix",
        max: 1,
        min: 0,
        step: 0.01,
        type: "slider",
      },
    ],
    type: "vocoder",
  }),
} as const;
