import { defineEffect } from "./param-types.js";
import { DEFAULT_WERKSTATT_SOURCE } from "./werkstatt-presets.js";

export const CONTAINER_EFFECT_DEFINITIONS = {
  frequencySplit: defineEffect({
    defaultConfig: {
      chains: [
        {
          effects: [],
          gain: 1,
          id: "low",
          muted: false,
          name: "Low",
          order: 0,
          pan: 0,
          solo: false,
        },
        {
          effects: [],
          gain: 1,
          id: "low-mid",
          muted: false,
          name: "Low Mid",
          order: 1,
          pan: 0,
          solo: false,
        },
        {
          effects: [],
          gain: 1,
          id: "high-mid",
          muted: false,
          name: "High Mid",
          order: 2,
          pan: 0,
          solo: false,
        },
        {
          effects: [],
          gain: 1,
          id: "high",
          muted: false,
          name: "High",
          order: 3,
          pan: 0,
          solo: false,
        },
      ],
      crossoverFrequencies: [200, 1000, 5000],
      dryWet: 1,
      enabled: false,
      frequencyBandCount: 4,
      inputGain: 1,
      outputGain: 1,
      type: "frequencySplit",
    },
    description: "Linkwitz-Riley multiband routing with one chain per band",
    name: "Frequency Split",
    params: [],
    type: "frequencySplit",
  }),

  fxComposite: defineEffect({
    defaultConfig: {
      chains: [
        {
          effects: [],
          gain: Math.SQRT1_2,
          id: "chain-a",
          muted: false,
          name: "Chain A",
          order: 0,
          pan: 0,
          solo: false,
        },
        {
          effects: [],
          gain: Math.SQRT1_2,
          id: "chain-b",
          muted: false,
          name: "Chain B",
          order: 1,
          pan: 0,
          solo: false,
        },
      ],
      dryWet: 1,
      enabled: false,
      inputGain: 1,
      outputGain: 1,
      type: "fxComposite",
    },
    description: "Parallel nested effect chains with branch mixing controls",
    name: "FX Composite",
    params: [],
    type: "fxComposite",
  }),

  stereoSplit: defineEffect({
    defaultConfig: {
      chains: [
        {
          effects: [],
          gain: 1,
          id: "left",
          muted: false,
          name: "Left",
          order: 0,
          pan: 0,
          solo: false,
        },
        {
          effects: [],
          gain: 1,
          id: "right",
          muted: false,
          name: "Right",
          order: 1,
          pan: 0,
          solo: false,
        },
      ],
      dryWet: 1,
      enabled: false,
      inputGain: 1,
      outputGain: 1,
      type: "stereoSplit",
    },
    description: "Separate nested effect chains for left and right channels",
    name: "Stereo Split",
    params: [],
    type: "stereoSplit",
  }),
  werkstatt: defineEffect({
    defaultConfig: {
      code: DEFAULT_WERKSTATT_SOURCE,
      dryWet: 1,
      enabled: false,
      inputGain: 1,
      outputGain: 1,
      parameters: {},
      samples: {},
      source: "return input;",
      type: "werkstatt",
    },
    description:
      "Client-side programmable DSP with declaration-driven controls",
    name: "Werkstatt",
    params: [],
    type: "werkstatt",
  }),
} as const;
