import {
  vocoderBandOptions,
  vocoderModulatorOptions,
} from "./effect-definition-shared.js";
import { defineEffect } from "./param-types.js";

export const DYNAMICS_EFFECT_DEFINITIONS = {
  compressor: defineEffect({
    type: "compressor",
    name: "Compressor",
    description:
      "Professional dynamics compressor with lookahead and auto attack/release",
    defaultConfig: {
      type: "compressor",
      enabled: false,
      threshold: -10,
      ratio: 4,
      attack: 2,
      release: 140,
      knee: 6,
      makeup: 0,
      mix: 1,
      lookahead: false,
      autoAttack: false,
      autoRelease: false,
      autoMakeup: true,
      inputgain: 0,
      automakeup: true,
      autoattack: false,
      autorelease: false,
      dryWet: 1.0,
      inputGain: 1.0,
      outputGain: 1.0,
    },
    visualization: "compressor-curve",
    params: [
      {
        type: "group",
        title: "Threshold & Ratio",
        children: [
          {
            type: "slider",
            key: "threshold",
            label: "Threshold",
            formatKey: "db",
            min: -60,
            max: 0,
            step: 0.5,
          },
          {
            type: "slider",
            key: "ratio",
            label: "Ratio",
            formatKey: "ratio",
            min: 1,
            max: 24,
            step: 0.1,
          },
        ],
      },
      {
        type: "group",
        title: "Timing",
        children: [
          {
            type: "slider",
            key: "attack",
            label: "Attack",
            formatKey: "milliseconds",
            min: 0,
            max: 100,
            step: 0.1,
          },
          {
            type: "slider",
            key: "release",
            label: "Release",
            formatKey: "milliseconds",
            min: 5,
            max: 1500,
            step: 1,
          },
        ],
      },
      {
        type: "slider",
        key: "knee",
        label: "Knee",
        formatKey: "db",
        min: 0,
        max: 24,
        step: 0.5,
      },
      {
        type: "slider",
        key: "makeup",
        label: "Device Makeup Gain",
        description:
          "Gain applied by the compressor after reduction and before the wrapper.",
        formatKey: "db",
        min: -40,
        max: 40,
        step: 0.5,
      },
      {
        type: "slider",
        key: "mix",
        label: "Device Mix",
        description:
          "Parallel blend inside the compressor; Effect Mix remains the outer wrapper blend.",
        formatKey: "percentage",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        type: "slider",
        key: "inputgain",
        label: "Device Input Gain",
        description:
          "Drives the compressor detector and processor before the wrapper mix.",
        formatKey: "db",
        min: -30,
        max: 30,
        step: 0.1,
      },
      {
        type: "group",
        title: "Auto Controls",
        children: [
          {
            type: "checkbox",
            key: "lookahead",
            label: "Lookahead (5ms)",
            description: "Enable lookahead for better transient handling",
          },
          {
            type: "checkbox",
            key: "autoattack",
            label: "Auto Attack",
            description: "Automatically adjust attack based on crest factor",
          },
          {
            type: "checkbox",
            key: "autorelease",
            label: "Auto Release",
            description: "Automatically adjust release based on crest factor",
          },
          {
            type: "checkbox",
            key: "automakeup",
            label: "Auto Makeup",
            description: "Automatically compensate for gain reduction",
          },
        ],
      },
    ],
  }),

  gate: defineEffect({
    type: "gate",
    name: "Gate",
    description: "Noise gate with hold, floor, inverse, and sidechain support",
    defaultConfig: {
      type: "gate",
      enabled: false,
      threshold: -6,
      return: 0,
      attack: 1,
      hold: 50,
      release: 100,
      floor: -72,
      inverse: false,
      dryWet: 1,
      inputGain: 1,
      outputGain: 1,
    },
    params: [
      {
        type: "slider",
        key: "threshold",
        label: "Threshold",
        formatKey: "db",
        min: -80,
        max: 0,
        step: 0.5,
      },
      {
        type: "slider",
        key: "return",
        label: "Return",
        formatKey: "db",
        min: 0,
        max: 24,
        step: 0.1,
      },
      {
        type: "group",
        title: "Envelope",
        children: [
          {
            type: "slider",
            key: "attack",
            label: "Attack",
            formatKey: "milliseconds",
            min: 0,
            max: 1000,
            step: 0.1,
          },
          {
            type: "slider",
            key: "hold",
            label: "Hold",
            formatKey: "milliseconds",
            min: 0,
            max: 500,
            step: 1,
          },
          {
            type: "slider",
            key: "release",
            label: "Release",
            formatKey: "milliseconds",
            min: 1,
            max: 2000,
            step: 1,
          },
        ],
      },
      {
        type: "slider",
        key: "floor",
        label: "Floor",
        formatKey: "db",
        min: -72,
        max: 0,
        step: 0.5,
      },
      {
        type: "checkbox",
        key: "inverse",
        label: "Inverse",
        description: "Duck the signal when the detector opens",
      },
    ],
  }),

  maximizer: defineEffect({
    type: "maximizer",
    name: "Maximizer",
    description: "Lookahead brickwall limiter with automatic makeup",
    defaultConfig: {
      type: "maximizer",
      enabled: false,
      threshold: -6,
      ceiling: -0.1,
      release: 100,
      lookahead: 5,
      lookaheadEnabled: true,
      dryWet: 1,
      inputGain: 1,
      outputGain: 1,
    },
    params: [
      {
        type: "slider",
        key: "threshold",
        label: "Threshold",
        formatKey: "db",
        min: -24,
        max: 0,
        step: 0.1,
      },
      {
        type: "checkbox",
        key: "lookaheadEnabled",
        label: "Lookahead",
      },
    ],
  }),

  vocoder: defineEffect({
    type: "vocoder",
    name: "Vocoder",
    description: "Multiband vocoder with noise, self, or external modulator",
    defaultConfig: {
      type: "vocoder",
      enabled: false,
      bands: 16,
      modulator: "self",
      carrierGain: 1,
      modulatorGain: 1,
      noise: 0,
      carrierMinFreq: 100,
      carrierMaxFreq: 12_000,
      modulatorMinFreq: 100,
      modulatorMaxFreq: 12_000,
      qStart: 20,
      qEnd: 2,
      envAttack: 5,
      envRelease: 30,
      gain: 0,
      mix: 1,
      bandCount: 16,
      modulatorSource: "noise-pink",
      dryWet: 1,
      inputGain: 1,
      outputGain: 1,
    },
    params: [
      {
        type: "select",
        key: "bandCount",
        label: "Bands",
        options: vocoderBandOptions,
        valueType: "number",
      },
      {
        type: "select",
        key: "modulatorSource",
        label: "Modulator",
        options: vocoderModulatorOptions,
      },
      {
        type: "group",
        title: "Carrier range",
        children: [
          {
            type: "slider",
            key: "carrierMinFreq",
            label: "Minimum",
            formatKey: "frequency",
            min: 20,
            max: 20_000,
            step: 1,
          },
          {
            type: "slider",
            key: "carrierMaxFreq",
            label: "Maximum",
            formatKey: "frequency",
            min: 20,
            max: 20_000,
            step: 1,
          },
        ],
      },
      {
        type: "group",
        title: "Modulator range",
        children: [
          {
            type: "slider",
            key: "modulatorMinFreq",
            label: "Minimum",
            formatKey: "frequency",
            min: 20,
            max: 20_000,
            step: 1,
          },
          {
            type: "slider",
            key: "modulatorMaxFreq",
            label: "Maximum",
            formatKey: "frequency",
            min: 20,
            max: 20_000,
            step: 1,
          },
        ],
      },
      {
        type: "group",
        title: "Filter bank",
        children: [
          {
            type: "slider",
            key: "qStart",
            label: "Q start",
            min: 1,
            max: 60,
            step: 0.1,
          },
          {
            type: "slider",
            key: "qEnd",
            label: "Q end",
            min: 1,
            max: 60,
            step: 0.1,
          },
        ],
      },
      {
        type: "group",
        title: "Envelope",
        children: [
          {
            type: "slider",
            key: "envAttack",
            label: "Attack",
            formatKey: "milliseconds",
            min: 0.1,
            max: 100,
            step: 0.1,
          },
          {
            type: "slider",
            key: "envRelease",
            label: "Release",
            formatKey: "milliseconds",
            min: 1,
            max: 1000,
            step: 1,
          },
        ],
      },
      {
        type: "slider",
        key: "gain",
        label: "Device Output Gain",
        description:
          "Native vocoder output level before the outer wrapper and Post-FX Trim.",
        formatKey: "db",
        min: -20,
        max: 20,
        step: 0.1,
      },
      {
        type: "slider",
        key: "mix",
        label: "Device Mix",
        description:
          "Blend inside the vocoder; Effect Mix remains the outer wrapper blend.",
        formatKey: "percentage",
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
  }),

  limiter: defineEffect({
    type: "limiter",
    name: "Limiter",
    description: "Transparent brick-wall limiter for output protection",
    defaultConfig: {
      type: "limiter",
      enabled: false,
      threshold: 0,
      dryWet: 1.0,
      inputGain: 1.0,
      outputGain: 1.0,
    },
    params: [
      {
        type: "group",
        title: "Limiter",
        children: [
          {
            type: "slider",
            key: "threshold",
            label: "Threshold",
            formatKey: "db",
            min: -60,
            max: 0,
            step: 0.1,
          },
        ],
      },
    ],
  }),
} as const;
