import {
  autotuneKeyOptions,
  autotuneScaleOptions,
  createBellBandGroup,
  createPassFilterGroup,
  createShelfBandGroup,
  distortionOversampleOptions,
  foldOversampleOptions,
  panLawOptions,
  waveshaperEquationOptions,
} from "./effect-definition-shared.js";
import { defineEffect } from "./param-types.js";

export const TONE_EFFECT_DEFINITIONS = {
  pitchShifter: defineEffect({
    type: "pitchShifter",
    name: "Pitch/Speed",
    description:
      "Speed-based pitch change (varispeed). Changes tempo proportionally with pitch.",
    defaultConfig: {
      type: "pitchShifter",
      enabled: false,
      pitchFactor: 1.0,
      dryWet: 1.0,
      inputGain: 1.0,
      outputGain: 1.0,
    },
    params: [
      {
        type: "group",
        title: "Pitch",
        children: [
          {
            type: "slider",
            key: "pitchFactor",
            label: "Pitch Factor",
            formatKey: "default",
            min: 0.25,
            max: 4.0,
            step: 0.01,
          },
        ],
      },
    ],
  }),

  distortion: defineEffect({
    type: "distortion",
    name: "Distortion",
    description: "Wave shaper distortion effect",
    defaultConfig: {
      type: "distortion",
      enabled: false,
      amount: 50,
      oversample: "2x",
      dryWet: 1.0,
      inputGain: 1.0,
      outputGain: 1.0,
    },
    params: [
      {
        type: "slider",
        key: "amount",
        label: "Amount",
        formatKey: "percentage100",
        min: 0,
        max: 100,
        step: 1,
      },
      {
        type: "select",
        key: "oversample",
        label: "Oversample",
        options: distortionOversampleOptions,
        valueType: "string",
      },
    ],
  }),

  crusher: defineEffect({
    type: "crusher",
    name: "Crusher",
    description: "Bit crusher effect with crush rate, bit depth, and boost",
    defaultConfig: {
      type: "crusher",
      enabled: false,
      crush: 0.5,
      bitDepth: 8,
      boost: 0,
      autoGain: true,
      dryWet: 1.0,
      inputGain: 1.0,
      outputGain: 1.0,
    },
    params: [
      {
        type: "slider",
        key: "crush",
        label: "Crush",
        formatKey: "percentage",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        type: "slider",
        key: "bitDepth",
        label: "Bit Depth",
        formatKey: "bits",
        min: 1,
        max: 16,
        step: 1,
      },
      {
        type: "slider",
        key: "boost",
        label: "Device Boost",
        description:
          "Native crusher boost; Auto Gain may compensate it before Post-FX Trim.",
        formatKey: "db",
        min: -40,
        max: 40,
        step: 0.1,
      },
      {
        type: "checkbox",
        key: "autoGain",
        label: "Auto Gain",
        description: "Automatically compensate for boost",
      },
    ],
  }),

  fold: defineEffect({
    type: "fold",
    name: "Fold",
    description: "Wave folding effect with amount, volume, and oversampling",
    defaultConfig: {
      type: "fold",
      enabled: false,
      amount: 0,
      volume: 0,
      oversample: 2,
      autoGain: true,
      dryWet: 1.0,
      inputGain: 1.0,
      outputGain: 1.0,
    },
    params: [
      {
        type: "slider",
        key: "amount",
        label: "Amount",
        formatKey: "db",
        min: -40,
        max: 40,
        step: 0.1,
      },
      {
        type: "slider",
        key: "volume",
        label: "Device Volume",
        description:
          "Native fold output level before the outer wrapper and Post-FX Trim.",
        formatKey: "db",
        min: -40,
        max: 40,
        step: 0.1,
      },
      {
        type: "select",
        key: "oversample",
        label: "Oversample",
        options: foldOversampleOptions,
        valueType: "number",
      },
      {
        type: "checkbox",
        key: "autoGain",
        label: "Auto Gain",
        description: "Automatically compensate for amount",
      },
    ],
  }),

  stereoTool: defineEffect({
    type: "stereoTool",
    name: "Stereo Tool",
    description: "Stereo manipulation with volume, width, and channel controls",
    defaultConfig: {
      type: "stereoTool",
      enabled: false,
      volume: 0,
      stereo: 0,
      panning: 0,
      panLaw: "equalPower",
      invertL: false,
      invertR: false,
      swap: false,
      dryWet: 1.0,
      inputGain: 1.0,
      outputGain: 1.0,
    },
    params: [
      {
        type: "slider",
        key: "volume",
        label: "Device Volume",
        description:
          "Native stereo-device level before the outer wrapper and Post-FX Trim.",
        formatKey: "db",
        min: -40,
        max: 40,
        step: 0.1,
      },
      {
        type: "slider",
        key: "stereo",
        label: "Stereo Width",
        formatKey: "percentage",
        min: -1,
        max: 1,
        step: 0.01,
      },
      {
        type: "slider",
        key: "panning",
        label: "Panning",
        formatKey: "pan",
        min: -1,
        max: 1,
        step: 0.01,
      },
      {
        type: "select",
        key: "panLaw",
        label: "Pan law",
        options: panLawOptions,
      },
      {
        type: "group",
        title: "Channel Options",
        children: [
          {
            type: "checkbox",
            key: "invertL",
            label: "Invert Left",
          },
          {
            type: "checkbox",
            key: "invertR",
            label: "Invert Right",
          },
          {
            type: "checkbox",
            key: "swap",
            label: "Swap Channels",
          },
        ],
      },
    ],
  }),

  revamp: defineEffect({
    type: "revamp",
    name: "7-Band EQ",
    description: "Parametric equalizer with 7 bands",
    defaultConfig: {
      type: "revamp",
      enabled: false,
      highPassEnabled: true,
      highPassFrequency: 20,
      highPassQ: Math.SQRT1_2,
      highPassOrder: 1,
      lowShelfEnabled: true,
      lowShelfFrequency: 80,
      lowShelfGain: 0,
      lowBellEnabled: true,
      lowBellFrequency: 200,
      lowBellGain: 0,
      lowBellQ: Math.SQRT1_2,
      midBellEnabled: true,
      midBellFrequency: 1000,
      midBellGain: 0,
      midBellQ: Math.SQRT1_2,
      highBellEnabled: true,
      highBellFrequency: 5000,
      highBellGain: 0,
      highBellQ: Math.SQRT1_2,
      highShelfEnabled: true,
      highShelfFrequency: 10_000,
      highShelfGain: 0,
      lowPassEnabled: true,
      lowPassFrequency: 20_000,
      lowPassQ: Math.SQRT1_2,
      lowPassOrder: 1,
      dryWet: 1.0,
      inputGain: 1.0,
      outputGain: 1.0,
    },
    visualization: "eq-curve",
    params: [
      createPassFilterGroup("highPass", "High Pass"),
      createShelfBandGroup("lowShelf", "Low Shelf"),
      createBellBandGroup("lowBell", "Low Bell"),
      createBellBandGroup("midBell", "Mid Bell"),
      createBellBandGroup("highBell", "High Bell"),
      createShelfBandGroup("highShelf", "High Shelf"),
      createPassFilterGroup("lowPass", "Low Pass"),
    ],
  }),

  waveshaper: defineEffect({
    type: "waveshaper",
    name: "Waveshaper",
    description: "Six selectable transfer curves with drive and output trim",
    defaultConfig: {
      type: "waveshaper",
      enabled: false,
      curve: "tanh",
      drive: 0,
      output: 0,
      equation: "hardclip",
      deviceInputGain: 0,
      deviceOutputGain: 0,
      mix: 1,
      dryWet: 1,
      inputGain: 1,
      outputGain: 1,
    },
    params: [
      {
        type: "select",
        key: "equation",
        label: "Equation",
        options: waveshaperEquationOptions,
      },
      {
        type: "slider",
        key: "deviceInputGain",
        label: "Device Input Gain",
        description:
          "Drive applied immediately before the shaping curve, after Pre-FX Trim.",
        formatKey: "db",
        min: 0,
        max: 40,
        step: 0.1,
      },
      {
        type: "slider",
        key: "deviceOutputGain",
        label: "Device Output Gain",
        description:
          "Native level after the shaping curve and before the wrapper.",
        formatKey: "db",
        min: -24,
        max: 24,
        step: 0.1,
      },
      {
        type: "slider",
        key: "mix",
        label: "Device Mix",
        description:
          "Blend inside the waveshaper; Effect Mix remains the outer wrapper blend.",
        formatKey: "percentage",
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
  }),

  neuralAmp: defineEffect({
    type: "neuralAmp",
    name: "Tone3000",
    description:
      "Local amp fallback; NAM model loading is gated and no credentials or models are bundled",
    defaultConfig: {
      type: "neuralAmp",
      enabled: false,
      modelId: null,
      modelUrl: null,
      modelName: null,
      modelData: null,
      input: 0,
      output: 0,
      cabinetEnabled: true,
      mono: true,
      mix: 1,
      dryWet: 1,
      inputGain: 1,
      outputGain: 1,
    },
    params: [
      {
        type: "slider",
        key: "input",
        label: "Device Input Gain",
        description: "Gain that drives the amp model after Pre-FX Trim.",
        formatKey: "db",
        min: -72,
        max: 12,
        step: 0.1,
      },
      {
        type: "slider",
        key: "output",
        label: "Device Output Gain",
        description: "Amp-model output level before the outer wrapper.",
        formatKey: "db",
        min: -72,
        max: 12,
        step: 0.1,
      },
      {
        type: "checkbox",
        key: "mono",
        label: "Mono",
      },
      {
        type: "slider",
        key: "mix",
        label: "Device Mix",
        description:
          "Blend inside Tone3000; Effect Mix remains the outer wrapper blend.",
        formatKey: "percentage",
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
  }),

  autotune: defineEffect({
    type: "autotune",
    name: "Autotune",
    description: "Monophonic pitch correction with key and scale controls",
    defaultConfig: {
      type: "autotune",
      enabled: false,
      key: "C",
      scale: "chromatic",
      amount: 1,
      retune: 40,
      retuneAmount: 0.5,
      shift: 0,
      smoothing: 0.5,
      smooth: 0.6,
      dryWet: 1,
      inputGain: 1,
      outputGain: 1,
    },
    params: [
      {
        type: "select",
        key: "key",
        label: "Key",
        options: autotuneKeyOptions,
      },
      {
        type: "select",
        key: "scale",
        label: "Scale",
        options: autotuneScaleOptions,
      },
      {
        type: "slider",
        key: "amount",
        label: "Amount",
        formatKey: "percentage",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        type: "slider",
        key: "retuneAmount",
        label: "Retune",
        formatKey: "percentage",
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        type: "slider",
        key: "shift",
        label: "Manual shift",
        formatKey: "semitones",
        min: -12,
        max: 12,
        step: 0.01,
      },
      {
        type: "slider",
        key: "smooth",
        label: "Smooth",
        formatKey: "percentage",
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
  }),
} as const;
