import {
  autotuneKeyOptions,
  autotuneScaleOptions,
  createBellBandGroup,
  createPassFilterGroup,
  createShelfBandGroup,
  distortionOversampleOptions,
  foldOversampleOptions,
  panLawOptions,
  waveshaperEquationOptions,
} from "./effect-definition-shared.js";
import { defineEffect } from "./param-types.js";

export const TONE_EFFECT_DEFINITIONS = {
  autotune: defineEffect({
    defaultConfig: {
      amount: 1,
      dryWet: 1,
      enabled: false,
      inputGain: 1,
      key: "C",
      outputGain: 1,
      retune: 40,
      retuneAmount: 0.5,
      scale: "chromatic",
      shift: 0,
      smooth: 0.6,
      smoothing: 0.5,
      type: "autotune",
    },
    description: "Monophonic pitch correction with key and scale controls",
    name: "Autotune",
    params: [
      {
        key: "key",
        label: "Key",
        options: autotuneKeyOptions,
        type: "select",
      },
      {
        key: "scale",
        label: "Scale",
        options: autotuneScaleOptions,
        type: "select",
      },
      {
        formatKey: "percentage",
        key: "amount",
        label: "Amount",
        max: 1,
        min: 0,
        step: 0.01,
        type: "slider",
      },
      {
        formatKey: "percentage",
        key: "retuneAmount",
        label: "Retune",
        max: 1,
        min: 0,
        step: 0.01,
        type: "slider",
      },
      {
        formatKey: "semitones",
        key: "shift",
        label: "Manual shift",
        max: 12,
        min: -12,
        step: 0.01,
        type: "slider",
      },
      {
        formatKey: "percentage",
        key: "smooth",
        label: "Smooth",
        max: 1,
        min: 0,
        step: 0.01,
        type: "slider",
      },
    ],
    type: "autotune",
  }),

  crusher: defineEffect({
    defaultConfig: {
      autoGain: true,
      bitDepth: 8,
      boost: 0,
      crush: 0.5,
      dryWet: 1.0,
      enabled: false,
      inputGain: 1.0,
      outputGain: 1.0,
      type: "crusher",
    },
    description: "Bit crusher effect with crush rate, bit depth, and boost",
    name: "Crusher",
    params: [
      {
        formatKey: "percentage",
        key: "crush",
        label: "Crush",
        max: 1,
        min: 0,
        step: 0.01,
        type: "slider",
      },
      {
        formatKey: "bits",
        key: "bitDepth",
        label: "Bit Depth",
        max: 16,
        min: 1,
        step: 1,
        type: "slider",
      },
      {
        description:
          "Native crusher boost; Auto Gain may compensate it before Post-FX Trim.",
        formatKey: "db",
        key: "boost",
        label: "Device Boost",
        max: 40,
        min: -40,
        step: 0.1,
        type: "slider",
      },
      {
        description: "Automatically compensate for boost",
        key: "autoGain",
        label: "Auto Gain",
        type: "checkbox",
      },
    ],
    type: "crusher",
  }),

  distortion: defineEffect({
    defaultConfig: {
      amount: 50,
      dryWet: 1.0,
      enabled: false,
      inputGain: 1.0,
      outputGain: 1.0,
      oversample: "2x",
      type: "distortion",
    },
    description: "Wave shaper distortion effect",
    name: "Distortion",
    params: [
      {
        formatKey: "percentage100",
        key: "amount",
        label: "Amount",
        max: 100,
        min: 0,
        step: 1,
        type: "slider",
      },
      {
        key: "oversample",
        label: "Oversample",
        options: distortionOversampleOptions,
        type: "select",
        valueType: "string",
      },
    ],
    type: "distortion",
  }),

  fold: defineEffect({
    defaultConfig: {
      amount: 0,
      autoGain: true,
      dryWet: 1.0,
      enabled: false,
      inputGain: 1.0,
      outputGain: 1.0,
      oversample: 2,
      type: "fold",
      volume: 0,
    },
    description: "Wave folding effect with amount, volume, and oversampling",
    name: "Fold",
    params: [
      {
        formatKey: "db",
        key: "amount",
        label: "Amount",
        max: 40,
        min: -40,
        step: 0.1,
        type: "slider",
      },
      {
        description:
          "Native fold output level before the outer wrapper and Post-FX Trim.",
        formatKey: "db",
        key: "volume",
        label: "Device Volume",
        max: 40,
        min: -40,
        step: 0.1,
        type: "slider",
      },
      {
        key: "oversample",
        label: "Oversample",
        options: foldOversampleOptions,
        type: "select",
        valueType: "number",
      },
      {
        description: "Automatically compensate for amount",
        key: "autoGain",
        label: "Auto Gain",
        type: "checkbox",
      },
    ],
    type: "fold",
  }),

  neuralAmp: defineEffect({
    defaultConfig: {
      cabinetEnabled: true,
      dryWet: 1,
      enabled: false,
      input: 0,
      inputGain: 1,
      mix: 1,
      modelData: null,
      modelId: null,
      modelName: null,
      modelUrl: null,
      mono: true,
      output: 0,
      outputGain: 1,
      type: "neuralAmp",
    },
    description:
      "Local amp fallback; NAM model loading is gated and no credentials or models are bundled",
    name: "Tone3000",
    params: [
      {
        description: "Gain that drives the amp model after Pre-FX Trim.",
        formatKey: "db",
        key: "input",
        label: "Device Input Gain",
        max: 12,
        min: -72,
        step: 0.1,
        type: "slider",
      },
      {
        description: "Amp-model output level before the outer wrapper.",
        formatKey: "db",
        key: "output",
        label: "Device Output Gain",
        max: 12,
        min: -72,
        step: 0.1,
        type: "slider",
      },
      {
        key: "mono",
        label: "Mono",
        type: "checkbox",
      },
      {
        description:
          "Blend inside Tone3000; Effect Mix remains the outer wrapper blend.",
        formatKey: "percentage",
        key: "mix",
        label: "Device Mix",
        max: 1,
        min: 0,
        step: 0.01,
        type: "slider",
      },
    ],
    type: "neuralAmp",
  }),
  pitchShifter: defineEffect({
    defaultConfig: {
      dryWet: 1.0,
      enabled: false,
      inputGain: 1.0,
      outputGain: 1.0,
      pitchFactor: 1.0,
      type: "pitchShifter",
    },
    description:
      "Speed-based pitch change (varispeed). Changes tempo proportionally with pitch.",
    name: "Pitch/Speed",
    params: [
      {
        children: [
          {
            formatKey: "default",
            key: "pitchFactor",
            label: "Pitch Factor",
            max: 4.0,
            min: 0.25,
            step: 0.01,
            type: "slider",
          },
        ],
        title: "Pitch",
        type: "group",
      },
    ],
    type: "pitchShifter",
  }),

  revamp: defineEffect({
    defaultConfig: {
      dryWet: 1.0,
      enabled: false,
      highBellEnabled: true,
      highBellFrequency: 5000,
      highBellGain: 0,
      highBellQ: Math.SQRT1_2,
      highPassEnabled: true,
      highPassFrequency: 20,
      highPassOrder: 1,
      highPassQ: Math.SQRT1_2,
      highShelfEnabled: true,
      highShelfFrequency: 10_000,
      highShelfGain: 0,
      inputGain: 1.0,
      lowBellEnabled: true,
      lowBellFrequency: 200,
      lowBellGain: 0,
      lowBellQ: Math.SQRT1_2,
      lowPassEnabled: true,
      lowPassFrequency: 20_000,
      lowPassOrder: 1,
      lowPassQ: Math.SQRT1_2,
      lowShelfEnabled: true,
      lowShelfFrequency: 80,
      lowShelfGain: 0,
      midBellEnabled: true,
      midBellFrequency: 1000,
      midBellGain: 0,
      midBellQ: Math.SQRT1_2,
      outputGain: 1.0,
      type: "revamp",
    },
    description: "Parametric equalizer with 7 bands",
    name: "7-Band EQ",
    params: [
      createPassFilterGroup("highPass", "High Pass"),
      createShelfBandGroup("lowShelf", "Low Shelf"),
      createBellBandGroup("lowBell", "Low Bell"),
      createBellBandGroup("midBell", "Mid Bell"),
      createBellBandGroup("highBell", "High Bell"),
      createShelfBandGroup("highShelf", "High Shelf"),
      createPassFilterGroup("lowPass", "Low Pass"),
    ],
    type: "revamp",
    visualization: "eq-curve",
  }),

  stereoTool: defineEffect({
    defaultConfig: {
      dryWet: 1.0,
      enabled: false,
      inputGain: 1.0,
      invertL: false,
      invertR: false,
      outputGain: 1.0,
      panLaw: "equalPower",
      panning: 0,
      stereo: 0,
      swap: false,
      type: "stereoTool",
      volume: 0,
    },
    description: "Stereo manipulation with volume, width, and channel controls",
    name: "Stereo Tool",
    params: [
      {
        description:
          "Native stereo-device level before the outer wrapper and Post-FX Trim.",
        formatKey: "db",
        key: "volume",
        label: "Device Volume",
        max: 40,
        min: -40,
        step: 0.1,
        type: "slider",
      },
      {
        formatKey: "percentage",
        key: "stereo",
        label: "Stereo Width",
        max: 1,
        min: -1,
        step: 0.01,
        type: "slider",
      },
      {
        formatKey: "pan",
        key: "panning",
        label: "Panning",
        max: 1,
        min: -1,
        step: 0.01,
        type: "slider",
      },
      {
        key: "panLaw",
        label: "Pan law",
        options: panLawOptions,
        type: "select",
      },
      {
        children: [
          {
            key: "invertL",
            label: "Invert Left",
            type: "checkbox",
          },
          {
            key: "invertR",
            label: "Invert Right",
            type: "checkbox",
          },
          {
            key: "swap",
            label: "Swap Channels",
            type: "checkbox",
          },
        ],
        title: "Channel Options",
        type: "group",
      },
    ],
    type: "stereoTool",
  }),

  waveshaper: defineEffect({
    defaultConfig: {
      curve: "tanh",
      deviceInputGain: 0,
      deviceOutputGain: 0,
      drive: 0,
      dryWet: 1,
      enabled: false,
      equation: "hardclip",
      inputGain: 1,
      mix: 1,
      output: 0,
      outputGain: 1,
      type: "waveshaper",
    },
    description: "Six selectable transfer curves with drive and output trim",
    name: "Waveshaper",
    params: [
      {
        key: "equation",
        label: "Equation",
        options: waveshaperEquationOptions,
        type: "select",
      },
      {
        description:
          "Drive applied immediately before the shaping curve, after Pre-FX Trim.",
        formatKey: "db",
        key: "deviceInputGain",
        label: "Device Input Gain",
        max: 40,
        min: 0,
        step: 0.1,
        type: "slider",
      },
      {
        description:
          "Native level after the shaping curve and before the wrapper.",
        formatKey: "db",
        key: "deviceOutputGain",
        label: "Device Output Gain",
        max: 24,
        min: -24,
        step: 0.1,
        type: "slider",
      },
      {
        description:
          "Blend inside the waveshaper; Effect Mix remains the outer wrapper blend.",
        formatKey: "percentage",
        key: "mix",
        label: "Device Mix",
        max: 1,
        min: 0,
        step: 0.01,
        type: "slider",
      },
    ],
    type: "waveshaper",
  }),
} as const;
