import {
  ClockIcon,
  FilterIcon,
  FireExtinguisherIcon,
  GaugeIcon,
  RadioIcon,
  WavesIcon,
  ZapIcon,
} from "lucide-react";
import type { EffectType } from "@/lib/audio";

export const EFFECT_ICONS: Record<EffectType, typeof FilterIcon> = {
  plateReverb: WavesIcon,
  pitchShifter: RadioIcon,
  delay: ClockIcon,
  distortion: ZapIcon,
  compressor: FireExtinguisherIcon,
  crusher: ZapIcon,
  fold: ZapIcon,
  stereoTool: RadioIcon,
  revamp: FilterIcon,
  tidal: WavesIcon,
  cheapReverb: WavesIcon,
  gate: FireExtinguisherIcon,
  waveshaper: ZapIcon,
  maximizer: GaugeIcon,
  vocoder: RadioIcon,
  neuralAmp: ZapIcon,
  werkstatt: FilterIcon,
  autotune: RadioIcon,
  fxComposite: FilterIcon,
  stereoSplit: RadioIcon,
  frequencySplit: FilterIcon,
  limiter: GaugeIcon,
};
